spring:
#  thymeleaf:
#    cache: false

  datasource:
    # EC2의 mariadb
    url: jdbc:mariadb://localhost:3306/myboard
    username: myadmin
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

    # 로컬의 mariadb
#    url: jdbc:mariadb://localhost:3306/myboard
#    username: myadmin
#    password: 123456
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: ture
        format_sql: true
        default_batch_fetch_size: 10

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

server:
  port: 8080
  address: 0.0.0.0